[package]
name = "udp-pb-server"
version = "0.1.0"
authors = ["raviteja <ravi.teja@atherenergy.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
tokio-codec = "0.1"
futures = "0.1"
log = "0.4"
pretty_env_logger = "0.3"

