[package]
name = "grpc-server"
version = "0.1.0"
authors = ["raviteja <ravi.teja@atherenergy.com>"]
edition = "2018"

[dependencies]
grpcio = { version = "0.4", default-features = false, features = ["protobuf-codec"] }
futures = "0.1"
protobuf = "2.2"
log = "0.4"
pretty_env_logger = "0.3"